os:
  - linux
  - windows

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"

matrix: # workaround for 3.7; see https://github.com/travis-ci/travis-ci/issues/9815
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - chmod +x .travis/push.sh

install:
install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qf $TRAVIS_COMMIT
  - pip install -r requirements.txt
  - pip install .

script: 
  - pytest --doctest-modules bamnostic/

