os:
  - linux
  - windows

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - pytest --doctest-modules

branches:
  only:
    - devel
    - master
after_success:
  if [ "$TRAVIS_BRANCH" == "devel" ]; then
    bash .travis/push.sh
  else
    :
fi