os:
  - linux
  - windows

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
  - "pypy3.5"

before_install:
  - chmod +x .travis/push.sh

install:
  - pip install -r requirements.txt
  - pip install .

script: 
<<<<<<< HEAD
  - pytest --doctest-modules
=======
  - pytest --doctest-modules bamnostic/
>>>>>>> devel

branches:
  only:
    - devel
<<<<<<< HEAD
    - master
after_success:
  if ([ "$TRAVIS_BRANCH" == "devel" ]) && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    bash .travis/push.sh
  else
    :
  fi
=======

jobs:
  include:
    - stage: deploy
      script: .travis/push.sh
      os: linux
      language: python
      python: "3.6"
>>>>>>> devel
