os:
  - linux
  - windows

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3.5"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
  - chmod +x .travis/push.sh

install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - pytest --doctest-modules bamnostic/

branches:
  only:
    - devel

jobs:
  include:
    - stage: deploy
      script: .travis/push.sh
      os: linux
      language: python
      python: "3.6"
