os:
  - linux
  - windows

language: python
python:
  - "2.7"
  - "3.6"
  - "pypy2.7"
  - "pypy3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .

script: pytest