os:
  - linux
  - windows

include:
  - python: 2.7
  - python: 3.4
  - python: 3.5
  - python: 3.6
  - python: 3.7-dev
  - python: pypy
  - python: pypy3.5

before_install:
  - chmod +x .travis/push.sh

install:
  - pip install -r requirements.txt
  - pip install .

script: 
  - pytest --doctest-modules bamnostic/

branches:
  only:
    - devel

jobs:
  include:
    - stage: deploy
      script: .travis/push.sh
      os: linux
      language: python
      python: "3.6"
